assignment3/assignment3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment3/myapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from myapp import views


app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/',views.about, name='about'), 
    path(r'courses/', views.courses, name='courses'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'courses/<int:cour_id>/', views.course_detail, name='course_detail'),
    path(r'login/', views.user_login, name='login'),
    path(r'logout/', views.user_logout, name='logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
    path(r'register/', views.register_student, name='register'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'forgot_password/', views.forgot_password, name='forgot_password'),
] 

assignment3/myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import *

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, blank=False, default="Development")

    def __str__(self):
      return self.name

class Course(models.Model):
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10,decimal_places=2, validators=[MinValueValidator(50), MaxValueValidator(500)])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)

    def __str__(self):
        #return f"{self.name}'s costs {self.price} and it {'is' if {self.for_everyone} else 'not'} for everyone"
        return self.name

   
    def discount(self):
        discount_to_apply = self.price * Decimal(0.1)  
        self.price  = self.price - discount_to_apply
        self.save() 
        #return self.price
             




class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'), ('CG', 'Calgery'),('MR', 'Montreal'), ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)
    profile_picture = models.ImageField(blank=True, null=True, upload_to='profile_pictures/', default='profile_pictures/default_profile_picture.jpeg')

    def __str__(self):
        return self.first_name



class Order(models.Model):
    ORDER_CHOICE = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=ORDER_CHOICE, default="1")
    order_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return f"{self.course.name} by {self.student.first_name} {self.student.last_name}"

    def total_cost(self):
        all_price = [price for price in self.course.price]
        return sum(all_price)

    def get_order_status_verbose(self):
        return dict(self.ORDER_CHOICE)[self.order_status]

assignment3/myapp/forms.py
from django import forms

from myapp.models import Order, Student


class InterestForm(forms.Form):
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=[(1, 'YES'), (2, 'NO')])
    levels = forms.IntegerField(initial=1, min_value=1) 
    comments= forms.CharField(widget=forms.Textarea, required=False, label="Additional Comments")

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['student', 'course', 'levels', 'order_date']
        widgets = {
            'student': forms.RadioSelect(),
            'order_date': forms.SelectDateWidget()
        }


class ProfilePictureUploadForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
    class Meta:
        model = Student
        fields = ['profile_picture', 'first_name', 'last_name', 'username']

assignment3/myapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Topic, Course, Student, Order
from .forms import OrderForm, InterestForm, ProfilePictureUploadForm
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from datetime import datetime


def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]
    if 'last_login' in request.session:
        last_login = request.session['last_login']
    else:
        last_login = 'Your last login was more than one hour ago'
    return render(request, 'myapp/index.html', {'top_list': top_list, 'last_login': last_login})


def about(request):
    if 'about_visits' in request.session:
        request.session['about_visits'] += 1
    else:
        request.session['about_visits'] = 1
        request.session.set_expiry(300)

    return render(request, 'myapp/about.html', {'about_visits': request.session['about_visits']})


def detail(request, top_no):
    topic = get_object_or_404(Topic, pk=top_no)
    courses = Course.objects.filter(topic=topic)
    return render(request, 'myapp/detail.html', {'topic': topic, 'courses': courses})  


def courses(request): 
    courlist = Course.objects.all().order_by('id') 
    return render(request, 'myapp/courses.html', {'courlist': courlist}) 


def place_order(request):
    msg = ''
    all_courses = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.course.price > 150:
                order.course.discount()
            if order.levels <= order.course.stages:
                order.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/place_order.html', {'form': form, 'msg': msg, 'courlist': all_courses})

@login_required(login_url='/myapp/login/')
def course_detail(request, cour_id):
    msg = ''
    course = get_object_or_404(Course, pk=cour_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['interested'] == '1':
                course.interested = course.interested + 1
                course.save()
            return redirect('myapp:index')
        else:
            msg = 'Something went wrong'
    else:
        form = InterestForm()
    return render(request, 'myapp/course_detail.html', {'msg': msg, 'course_info': course, 'form': form})



def user_login(request):
    if request.method == 'POST':
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            print("Cookie Working")
        else:
            print("Not Working Cookie")
        username = request.POST['username']
        password = request.POST['password']
        next = request.POST.get('next',None)
        #print(f'Username: {username})
        
        user = authenticate(username=username, password=password) 
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.now())
                request.session.set_expiry(0) 
                if not next:
                    return HttpResponseRedirect(reverse('myapp:index'))
                
                return HttpResponseRedirect(next)
            else:
                return HttpResponse('Your account is disabled.')
        
        else:return HttpResponse('Invalid login details.') 
    else:
        if request.user.is_authenticated:
            return redirect('myapp:index')
        request.session.set_test_cookie()
        username_to_fill = request.GET.get('username', None) 
        print(username_to_fill)
        return render(request, 'myapp/login.html', {'username_to_fill': username_to_fill})
    
    
        
        
@login_required(login_url='/myapp/login/')
def user_logout(request):
    for key in list(request.session.keys()):
        del request.session[key]
    return HttpResponseRedirect(reverse('myapp:index'))

@login_required(login_url='/myapp/login/') 
def myaccount(request):
    username = request.user.username 
    try:   
        user = Student.objects.filter(username=username)
    except: 
        user = None

    if request.method == 'POST':
        profile_picture_upload_form = ProfilePictureUploadForm(request.POST, request.FILES, instance=user[0])
        password = request.POST['password']
        if profile_picture_upload_form.is_valid():
            user_object = profile_picture_upload_form.save()
            if password: 
                user_object.set_password(password)
                user_object.save()

        return redirect('myapp:myaccount')

   
    is_student = False
    orders = None 
    if user:
        is_student = True
        orders = Order.objects.filter(student=user[0])
        topics = Student.objects.get(username=username).interested_in.values()
        if len(topics) == 0:
            topics = []
        profile_picture_upload_form = ProfilePictureUploadForm(instance=user[0])
        #print(orders)    
        #print(topics)
        return render(request, 'myapp/myaccount.html', {'user':user[0],'is_student': is_student, 'orders': orders, 'topics': topics, 'form':profile_picture_upload_form})
    
    return render(request, 'myapp/myaccount.html', {'is_student':is_student})


def register_student(request):

    if request.method == 'POST':


        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']


        try:
            student = get_object_or_404(Student, username=username)
        except:     
            student = None

        if not username or not password:
            return render(request, 'myapp/register.html', {'error_message': 'Either username or password or both have not been passed'})

        if student:
            return render(request, 'myapp/register.html', {'error_message': 'User already exists with the given username'})

        
        student = Student.objects.create_user(username=username, password=password, email=email)
        student.first_name = username  
        student.save()

        return redirect(reverse('myapp:login') + f'?username={username}')



    if request.user.is_authenticated:
        return redirect('myapp:index')
    return render(request, 'myapp/register.html')


@login_required(login_url='/myapp/login/')
def myorders(request):
    try: 
        student = Student.objects.get(username=request.user.username)
    except Student.DoesNotExist:
        student = None

    if not student:   
        return render(request, 'myapp/myorders.html', {'error_message':'You are not a registered student'})

    orders = Order.objects.filter(student=student) 
    if not orders:
        print('Inside')
        return render(request, 'myapp/myorders.html', {'error_message': 'You do not have any orders'})      
    return render(request, 'myapp/myorders.html', {'orders':orders})   


@login_required(login_url='/myapp/login/')
def handle_image_upload(request):    
    if request.method == 'POST':  
        pass


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        student = Student.objects.get(email=email)

        if student: 
            random_password = Student.objects.make_random_password()   
            #print(random_password)    
            student.set_password(random_password)
            student.save()
            send_mail(
                
                subject=f'{student.first_name}: Here is your new password', 
                message=f'Your new password is: {random_password}. Please change your password from myaccount page',
                from_email = "dm.25041998@gmail.com" ,
                recipient_list=[student.email,],
                fail_silently=False
            
            )

        return  redirect('myapp:login')



        
    return render(request, 'myapp/forgot_password.html')

assignment3/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}
    About
{% endblock %}
{% block body_block %}

    <h1>This is an E-learning Website! Search our Topics to find all available Courses.</h1>
    <h2>About Visits: {{about_visits}}</h2>

    
    
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p>#}
{{form}}
{% endblock %}

assignment3/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
 <meta charset="UTF-8">
 <title>E-Learning WebApp!</title>
</head>
<body>
    <p><a href="/myapp">Home</a> (Using Hard Coded URL)</p>
    <p><a href="{% url 'myapp:index' %}">Home</a>(Using URL namespacing)</p>
    <h3><b>This is an E-learning Website! Search our Topics to find all available Courses.</b></h3>
</body>
</html>

assignment3/myapp/templates/myapp/base.html
<!DOCTYPE html>

{% load static %}

<html>

<head>

<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />

<title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>

<body>

<div>

<!-- 

    {% if not request.user.is_authenticated %}     
    <a href="{% url 'myapp:login' %}">Login</a>
    <a href="{% url 'myapp:register' %}">Register</a>
    

{% else %}  
    <a href="{% url 'myapp:logout' %}">Logout</a>
    <h1>{% block myhdg %}Hello {{request.user.first_name}} {% endblock %}</h1>
{% endif %}


-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">E - Learning Web App</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'myapp:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:courses' %}">Courses</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:place_order' %}">Place Order</a>
          </li>

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:myorders' %}">My Orders</a>
            </li>
          {% endif %}
          
        </ul>
        <div class="d-flex">

          {% if not request.user.is_authenticated %}     
            <a class="btn btn-primary" style="margin-right: 6px;" href="{% url 'myapp:login' %}">Login</a>
            <a class="btn btn-primary" href="{% url 'myapp:register' %}">Register</a>
    

          {% else %}  
            <a href="#" class="navbar-brand">Hello {{request.user.first_name}}</a>
            <a class="btn btn-primary" style="margin-right: 6px;" href="{% url 'myapp:logout' %}">Logout</a>
            <a class="btn btn-primary" href="{% url 'myapp:myaccount' %}">My Account</a>
            
        {% endif %}



            

        </div>
       
      </div>
    </div>
  </nav>





<div class="container">

    {% block body_block %}{% endblock %}

    <hr />
    <div class="row" style="text-align:center;">
      <div class="col-md-4"><a href="/myapp/about/">Find out about our E-Learning site</a></div>
      <div class="col-md-4"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a></div>
      <div class="col-md-4"><a href = "{% url 'myapp:courses' %}">Click here to check all Courses</a></div>
    </div>

</div>



</div>






</body>

</html>

assignment3/myapp/templates/myapp/course_detail.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
    Course Details
{% endblock %}
{% block body_block %}
    <p><b>Name:</b> {{ course_info.name }} </p>
    <p><b>Number of People Interested:</b> {{ course_info.interested }}</p>
    <p><b>Price:</b> {{ course_info.price }} </p>

    {% if course_info.for_everyone %}
        <form method="POST">
            {% csrf_token %}
            {{ form| crispy }}
            <input class="btn btn-primary" type="submit" value="Submit"/>
        </form>
    {% else %}
        <p> Unfortunately, this course is not for everyone </p>
    {% endif %}
    <p> {{ msg }}</p>
{% endblock %}

assignment3/myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block title %}
    Courses
{% endblock %}
{% block body_block %}
    <h3 align="center">List of Courses: </h1>
    <div class="row">
    {% for course in courlist %}

    <div class="card text-center col-md-4 text-dark">
        <div class="card-header">
          {{course.name}}
        </div>
        <div class="card-body">
          <a href="{% url 'myapp:course_detail' course.id %}" class="btn btn-success">More Details</a>
        </div>
        <div class="card-footer text-muted">
          Price: <strong>{{course.price}}</strong>
        </div>
      </div>


    {% endfor %}
    </div>
    <br />
    <br />
   <a class="btn btn-primary" href="/myapp/place_order">Purchase Course</a>
{% endblock %}

assignment3/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}
    Details
{% endblock %}
{% block body_block %}
    <p><b>Topic:</b> {{ topic.name }} </p>
    <p><b>Category:</b> {{ topic.category }}</p>

    <ul>
        {% for course in courses %}  
        
        <li>{{course.name}}</li>
        
        {% endfor %}
    </ul>
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p> #}
{% endblock %}

assignment3/myapp/templates/myapp/detail0.html
{% extends 'myapp/base.html' %}

{% block body_block %}

<p><a href="{% url 'myapp:index' %}">Home</a></p>
<h1 align="center">{{topic.name}}</h1>
<h3 align="center">Category: {{topic.category}}</h3>
<h4>Course for {{topic.name}}</h4>
<ul>
{% for course in courses %}  

<li>{{course.name}}</li>

{% endfor %}
</ul>


{% endblock %}

assignment3/myapp/templates/myapp/forgot_password.html
{% extends 'myapp/base.html' %}
{% block title %}
    Forgot Password
{% endblock %}
{% block body_block %}
    <h2>Forgot Password</h2>
   <form action="{% url 'myapp:forgot_password' %}" method="POST">
    {% csrf_token %}
    <p>
        <label for="username">Enter Your Email</label>
        <input type="email" name="email" required /> 
    </p>

    <p>
        <input class="btn btn-primary" type="submit">
    </p>
   </form>
    </ul>
{% endblock %}

assignment3/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
 <meta charset="UTF-8">
 <title>E-Learning WebApp!</title>
</head>
<body>
 {% if top_list %}
 <h2>List of Topics</h2>
 <ol>
 {% for top in top_list %}
 <li> <a href="{% url 'myapp:detail' top.id %}">{{ top.name}}</a></li>
 {% endfor %}
 </ol>
 {% else %}
 <strong>There are no available topics!</strong>
 {% endif %}

 <p><a href="/myapp/about">About page</a> (Using Hard Coded URL)</p>
 <p><a href="{% url 'myapp:about' %}">About page</a>(Using URL namespacing)</p>

</body>
</html>

assignment3/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block title %}
    Login
{% endblock %}
{% block body_block %}
    <br />
    <br />
    <h2 align="center">Login</h2>
    <!--
   <form action="{% url 'myapp:login' %}" method="POST">
    {% csrf_token %}
    <p>
        <label for="username">Username</label>
        <input type="text" name="username" id="username" class="username" value="{{username_to_fill|default_if_none:''}}" /> 
    </p>

    <p>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="password" />
        <input type="hidden" name="next" value="{{request.GET.next}}" />
    </p>

    <p>
        <input type="submit">
    </p>
   </form> -->
   <div class="login_form" style="max-width: 900px; margin: auto;">
    <form action="{% url 'myapp:login' %}" method="POST">
        {% csrf_token %}
        <div class="row mb-3">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
            <input type="text" name="username" class="form-control" id="inputEmail3" value="{{username_to_fill|default_if_none:''}}">
        </div>
        </div>
        <div class="row mb-3">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
        <div class="col-sm-10">
            <input name="password" type="password" class="form-control" id="inputPassword3">
        </div>
        </div>
        <input type="hidden" name="next" value="{{request.GET.next}}" />
        <div class="login_submit_button" style="text-align: center;">

            <button type="submit" class="btn btn-primary">Log In</button>
            <br />
            <br />
            <p><a href="{% url 'myapp:forgot_password' %}" >Forgot Password?</a></p>

        </div>
        
        
    </form>
  </div>
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p> #}
{% endblock %}

assignment3/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    My Account
{% endblock %}
{% block body_block %}
    {% if is_student %}
    <h2>Welcome: {{request.user.first_name}}  {{request.user.last_name}}</h2></h2>
    <div class="row">
        <div class="col-md-3">
        {% if not user.profile_picture %}
        <img height="200px" width="200px" src="/media/profile_pictures/default_profile_picture.jpeg" alt="">
        {% else %}
        <img height="200px" width="200px" src="{{user.profile_picture.url}}" alt="">
        {% endif %}
        </div>
    </div>
    {% else %}
    <h2>You're not a registered student</h2>
    {% endif %}
    <hr />
    <br />
    <div class="row">
    {% if orders %}
    <h2>Orders: </h2>
    {% for order in orders %}
    <!--
    <li><h4>{{order.course.name}} - {{order.order_date}}</h4>
    
    </li>
    -->
    <div class="col-md-4">
        <div class="card text-center">
            <div class="card-header">
              Order: {{order.pk}}
            </div>
            <div class="card-body">
              <h5 class="card-title">{{order.course.name}}</h5>
              <p class="card-text">{{order.order_date}}</p>
              <p class="card-text">Price: ${{order.course.price}}</p>
            </div>
            <div class="card-footer text-muted">
                Order Status: {{order.get_order_status_verbose}}
            </div>
          </div>
    </div>
    {% endfor %}

    {% endif %}
    </div>
    <hr />
    <br />
    {% if topics %}
    <h2>Topics Interested In: </h2>
    <ul>
    {% for topic in topics %}

    <li>{{topic.name}}</li>

    {% endfor %}
    </ul>

    <hr />
    <br />

    <h2>Update Profile </h2>
    <form action="{% url 'myapp:myaccount' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" />
    </form>
    {% endif %}

    
    
{#    <p><a href="{% url 'myapp:index' %}">Go Back</a></p> #}
{% endblock %}

assignment3/myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block title %}
    My Orders
{% endblock %}
{% block body_block %}
    {% if error_message %}          
        <h2>{{error_message}}</h2>

    {% else %}
        <h2 align="center">{{request.user.first_name}}'s orders: </h2>
            <div class="row">
                    {% if orders %}

                    {% for order in orders %}  

                        <div class="col-md-4">
                            <div class="card text-center">
                                <div class="card-header">
                                  Order: {{order.pk}}
                                </div>
                                <div class="card-body">
                                  <h5 class="card-title">{{order.course.name}}</h5>
                                  <p class="card-text">{{order.order_date}}</p>
                                  <p class="card-text">Price: ${{order.course.price}}</p>
                                </div>
                                <div class="card-footer text-muted">
                                    Order Status: {{order.get_order_status_verbose}}
                                </div>
                              </div>
                        </div>

                    {% endfor %}
                    {% else %}
                    <h3 align="center">You have not placed any order</h3>
                    {% endif %}

            </div>
    {% endif %}
{% endblock %}

assignment3/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %}
    Order Response
{% endblock %}
{% block body_block %}
    <p> {{ msg }}</p>
{% endblock %}

assignment3/myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_filters %}
% load crispy_forms_tags %}
{% block title %}
    Place Order
{% endblock %}
{% block body_block %}

    <h2 align="center">Place Order</h2>
    <br />
    <ul>
        {% for course in courlist %}
            <li>{{ course.name }} = ${{ course.price }}</li>
        {% endfor %}
    </ul>
    <div class="place_order_form" style="max-width:900px; margin: auto;">
        <form method="POST">
            {% csrf_token %}
            {{ form| crispy }}
            <input class="btn btn-primary" type="submit" value="Submit"/>
        </form>
    </div>
    
    <p> {{ msg }}</p>
{% endblock %}